settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-flexarray, ontap-automation

sidebar:
  entries:
    - title: ONTAP docs
      url: /index.html
    - title: Release Notes
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - section: introduction-concepts
    - section: setup-upgrade
    - section: cluster-admin
    - section: volume-admin
    - section: network-management
    - section: nas-management
    - section: san-management
    - section: object-storage-management
    - section: security-encryption
    - section: data-protection-disaster-recovery
    - section: event-performance-monitoring
    - title: ONTAP manual pages 
      url: https://docs.netapp.com/us-en/ontap-cli-9111/index.html
    - title: Legal notices
      url: /reference_legal_notices.html

